const int BACKGROUND_COLOR = 0xFFFFFFFF;
const int SECONDARY_COLOR = 0xFF4FC9CA;
const int PRIMARY_COLOR = 0xFF4FC9CA;
const int GRADIENT_COLOR = 0xFFF0FDFD;
const int INACTIVE_COLOR = 0xFFCBCBCB;
const int WHITE_COLOR = 0xFFFFFFFF;
const int BLACK_COLOR = 0xFF000000;